USE [master]
GO

/****** Object:  Database [ABC_SHOP]    Script Date: 10/16/2014 9:07:42 PM ******/
CREATE DATABASE [ABC_SHOP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ABC_SHOP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\ABC_SHOP.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ABC_SHOP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\ABC_SHOP_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ABC_SHOP] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ABC_SHOP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ABC_SHOP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ABC_SHOP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ABC_SHOP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ABC_SHOP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ABC_SHOP] SET ARITHABORT OFF 
GO

ALTER DATABASE [ABC_SHOP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ABC_SHOP] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ABC_SHOP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ABC_SHOP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ABC_SHOP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ABC_SHOP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ABC_SHOP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ABC_SHOP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ABC_SHOP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ABC_SHOP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ABC_SHOP] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ABC_SHOP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ABC_SHOP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ABC_SHOP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ABC_SHOP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ABC_SHOP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ABC_SHOP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ABC_SHOP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ABC_SHOP] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ABC_SHOP] SET  MULTI_USER 
GO

ALTER DATABASE [ABC_SHOP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ABC_SHOP] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ABC_SHOP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ABC_SHOP] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ABC_SHOP] SET  READ_WRITE 
GO


